import type { SimpleIcon } from 'simple-icons';
import {
  siBootstrap,
  siDocker,
  siFigma,
  siGit,
  siHtml5,
  siJavascript,
  siLess,
  siMui,
  siNextdotjs,
  siReact,
  siReacthookform,
  siSass,
  siShadcnui,
  siStyledcomponents,
  siSwiper,
  siTailwindcss,
  siTypescript,
  siVite,
  siWebpack,
  siWordpress,
  siZod,
} from 'simple-icons';

/** Локальные SVG-path из simple-icons — без внешних запросов к CDN */
export const SIMPLE_ICON_MAP: Record<string, SimpleIcon> = {
  html5: siHtml5,
  nextdotjs: siNextdotjs,
  react: siReact,
  sass: siSass,
  less: siLess,
  bootstrap: siBootstrap,
  shadcnui: siShadcnui,
  typescript: siTypescript,
  javascript: siJavascript,
  mui: siMui,
  tailwindcss: siTailwindcss,
  styledcomponents: siStyledcomponents,
  reacthookform: siReacthookform,
  zod: siZod,
  swiper: siSwiper,
  wordpress: siWordpress,
  git: siGit,
  docker: siDocker,
  vite: siVite,
  webpack: siWebpack,
  figma: siFigma,
};
