/** Профиль — меняйте здесь, данные подставятся по всему сайту */

export const PROFILE = {
  firstName: 'Руслан',
  lastName: 'Рысбеков',
  middleName: 'Замирович',
  fullName: 'Рысбеков Руслан Замирович',
  initials: 'РР',
  displayName: 'Руслан',
  title: 'Фронтенд-разработчик',
  titleShort: 'Фронтенд-разработчик',
  portfolioTagline: 'Персональное портфолио — мои проекты, стек и опыт работы',
  birthDate: '18 июня 1996',
  age: 29,
  city: 'Сочи',
  location: 'Россия, г. Сочи',
  relocation: 'Не готов к переезду',
  businessTrips: 'Готов к командировкам',
  citizenship: 'Россия',
  employer: 'ИП Барков',
  employerRole: 'Фронтенд-разработчик',
  projectsCount: 7,
  email: 'dannykg1996@gmail.com',
  phone: '+7 (977) 494-52-35',
  phoneTel: '+79774945235',
  whatsapp: 'https://wa.me/79774945235',
  viber: 'viber://chat?number=79774945235',
  telegram: 'https://t.me/danny_KG',
  telegramHandle: '@danny_KG',
  github: 'https://github.com/DannyKGZ',
  gitlab: 'http://82.146.55.239/Dannykg1996',
  hh: 'https://sochi.hh.ru/resume/6b1a369bff0dcf2d5e0039ed1f6c3779613774',
  resumePath: '/profile.pdf',
  resumeFileName: 'Рысбеков-Руслан-резюме.pdf',
  employment: [
    'Полная занятость',
    'Частичная занятость',
    'Проектная работа',
  ],
  education: {
    institution: 'ТМТТ',
    specialty: 'Слесарь, Автомеханик',
    year: 2016,
    level: 'Среднее специальное образование',
  },
  languages: [{ name: 'Русский', level: 'Родной' }],
  preloaderText: 'Добро пожаловать на моё портфолио',
  careerStory:
    'Раньше работал машинистом Московского метро. Увидел, как друзья-разработчики работают удалённо, уволился и начал самоучкой изучать программирование. С октября 2023 года — коммерческая фронтенд-разработка.',
} as const;

export const WORK_EXPERIENCE = {
  startMonth: 'Октябрь',
  startYear: 2023,
  period: 'Октябрь 2023 — сейчас',
  duration: '1 год 9 месяцев',
  durationShort: '1 год 9 мес',
  since: 'с октября 2023 года',
} as const;
